zdavatz/spreadsheet

lib/spreadsheet/excel/worksheet.rb
[This file](https://yadi.sk/i/RrJgBR8He9CB7) causes `ArgumentError: comparison of NilClass with 0 failed` when #dimensions is called on a worksheet.
How to reproduce:
```
require 'spreadsheet'
ss = Spreadsheet.open 'spreadsheet_dimensions_error.xls'
ss.worksheets.last.dimensions
```
Fix by [Kolmetoista](https://github.com/kolmetoista)
=> Fixing Excel::Worksheet#dimensions

Gemfile.lock
`ruby-ole` <= `1.2.11.7` throws a duplicated key warning in Ruby 2.2.
This commit updates `ruby-ole` to `1.2.11.8`, which fixes this warning.
Related discussion: [aquasync/ruby-ole#15]
[aquasync/ruby-ole#15]: https://github.com/aquasync/ruby-ole/issues/15
=> Update `ruby-ole` to `1.2.11.8`

lib/spreadsheet/format.rb, spreadsheet.gemspec, test/format.rb
I had a problem with read a file when some cells had format like "0.00;[RED]\\-0.00' - and this recognized as date.
=> add format for nubmer with out #

lib/spreadsheet/excel/writer/worksheet.rb
A `puts` instruction pollutes the log and doesn't serve any purpose. As such, we propose its removal.
=> Remove stray puts

lib/spreadsheet/format.rb, test/format.rb
We had a report of certain spreadsheets not being read correctly by our application. Investigation showed that depending on the date/time format, cells containing a date were sometimes being returned as fractional days.
We determined that the number format for these cells included the string "[$-409]" before the datetime formatting. Cells are checked to see if they are numbers before anything else, and since the presence of "0" causes the `:number` regex to match, the datetime checks never occur.
"[$-nnn]" is Excel formatting code that controls which locale is used to render the date. It's not relevant to determine the type of data in the field, so we are just removing it from the string before testing it with the regex.
As far as we can tell, this format was produced by Excel itself. …
=> Disregard locale indicators in number format

lib/spreadsheet/excel/internals.rb
I got a error message - "Unknown Codepage 0x5212", when I opened an excel file.
The excel is created by JExcelAPI with 'Big5' encoding.
I found the file's codepage_id is 21010.
Then I solved it using "UTF-16LE" encoding.
Signed-off-by: ChouAndy <chouandy@ecoworkinc.com>
=> Fixed Unknown Codepage 0x5212

lib/spreadsheet.rb, lib/spreadsheet/encodings.rb
This fix is related to a bug in the iconv implementation packaged with libc6 on Ubuntu 12.04.
The (known) ruby version affected is 1.8.7.
For some reasons, the encoding options ```//TRANSLIT//IGNORE``` seem to be improperly applied. When ```//TRANSLIT``` is specified, instead of rescuing errors related to ```//TRANSLIT``` and checking if the ```//IGNORE``` is set, the code simply crashes.
I would like to be able to disable ```//TRANSLIT``` for that specific use case and so I moved the encoding options to attribute accessors on the Spreadsheet module.
=> Fix issue with iconv on Ubuntu 12.04

lib/spreadsheet/excel/workbook.rb
That variable cannot be garbage collected and it retains a lot of memory.
Would be great if you can consider this change and made a new release of this gem.
=> Avoid creating a class variable

lib/spreadsheet/excel/internals.rb
PR #161 created an issue (#189) where an invalid code page is used when writing the workbook using the default encoding UTF-16LE.  This PR will remove the invalid codes from the list used to look up code page identifiers by name so it returns the correct code page for UTF-16LE, MACROMAN, and WINDOWS-1252.
=> Use codepage 1200 when writing UTF-16LE files

lib/spreadsheet/worksheet.rb
Running rake resulted in the following warning: `lib/spreadsheet/worksheet.rb:345: warning: shadowing outer local variable - i`; this patch fixes that.
=> shadowing outer local variable - i

.travis.yml, lib/spreadsheet/excel/reader.rb
When running specs that depend on spreadsheet (or roo-xls) there is the
following warning: lib/spreadsheet/excel/reader.rb:402: warning:
assigned but unused variable - len.
[suppress-unused-var-warning-in-roo-xls]
=> Suppresses assigned but unused var warnings

.travis.yml, Gemfile.lock, lib/spreadsheet/excel/reader.rb, spreadsheet.gemspec, test/integration.rb
- Bumps gems
- Fixes remaining warnings in specs (see also https://github.com/zdavatz/spreadsheet/pull/226)
Before:
After:
[fixes-remaining-spec-warnings-and-updates-gemspec]
=> Fixes remaining spec warnings and updates gemspec

lib/spreadsheet/worksheet.rb, test/worksheet.rb
Hey team,
Have been enjoying using this gem in my own projects - nice work!
One thing I've found to be limiting is the inability to treat `Worksheet#each` as you would `Enumerable#each`. For example you are unable to use `worksheet.each(1).with_index`. 
This PR adds in that functionality by returning an enumerable object when no block is provided immediately to `each`.
For example you can now do:
`worksheet.each(1).with_index do |row, index|`
It also respects the previous syntax and still allows:
`worksheet.each(1) do |row|`
I've written specs for both cases.
This is my first open source contribution so let me know if anything needs to be changed!
=> Add ability to chain methods to `Worksheet#each`

lib/spreadsheet/excel/reader/biff8.rb
Hi,
I got `FrozenError` error when I use spreadsheet gem with `--enable-frozen-string-literal` option.
```
FrozenError:
can't modify frozen String
```
This PR is to fix the above error.
=> fixed FrozenError caused by frozen-string-literal

Manifest.txt, lib/spreadsheet.rb, lib/spreadsheet/version.rb, spreadsheet.gemspec, test/integration.rb
Hi,
To use my forked `spreadsheet` and `ruby-ole` gems, I add dependencies to my GEMFILE like below.
```ruby
if !ENV['USE_ORIGINAL_DEPENDENCIES']
['spreadsheet', 'rubyzip', 'ruby-ole'].each do |library|
library_path = File.expand_path("../#{library}", __dir__)
if Dir.exist?(library_path) && !ENV['USE_GITHUB_REPOSITORY']
gem library, path: library_path
else
gem library, git: "https://github.com/taichi-ishitani/#{library}.git"
end
end
end
```
However, gem installation failed due to following error:
https://travis-ci.org/rggen/rggen-spreadsheet-loader/jobs/499367300#L904
```
[!] There was an error while loading `spreadsheet.gemspec`: cannot load such file -- ole/storage
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.
>  require 'spreadsheet' …
```
=> Move declaration of VERSION to an individual file

.gitignore, .travis.yml, Gemfile
Hi,
The latest `ruby-ole` gem including my PR (aquasync/ruby-ole#24) has been released.
Therefore, I removed workaround for installation of `ruby-ole` gem from `Gemfile` file.
=> Remove workaround for ruby-ole gem

lib/spreadsheet/format.rb, test/format.rb
I have an excel using the format `[$-C0A]dd\\-mmm\\-yy` for dates (ex: `23-oct.-2019`), and the latest stable version recognizes that format as a number instead of a date. This PR tries to fix that issue.
=> Fixes unrecognized date format

.travis.yml, lib/spreadsheet/worksheet.rb
Add instance method "<<" to Spreadsheet::Worksheet for duck typing with CSV library.
=> add instance method "<<" to Spreadsheet::Worksheet

GUIDE.md
If a cell contains more than 32KB of data, Excel will interpret this as file corruption
Resolves #250
=> Add note to guide explaining cell content length limit

lib/spreadsheet/worksheet.rb
related to PR #249
when sheet is empty, `last_row_index` return 0. `#<<` actually adds data to the second row. leaving the first row blank.
to reproduce:
```ruby
require 'spreadsheet'
wb = Spreadsheet::Workbook.new
sheet = wb.create_worksheet
sheet << ['A', 'B', 'C', 'D']
sheet << [1,2,3,4]
wb.write(File.expand_path('spreadsheet.xls', Dir.pwd))
```
=> fix: Worksheet#<< fails to add data to the first row

lib/spreadsheet/worksheet.rb, test/worksheet.rb
Based on http://www.excelcodex.com/2012/06/worksheets-naming-conventions/ (and reported in #70) this removes any invalid worksheet characters (`\ , / , * , ? , : , [ , ]`) from the name and replaces them with underscores.
=> Remove invalid worksheet characters

spreadsheet.gemspec
Running code that uses the spreadsheet gem with Ruby 3.3.0 causes the following warning to be shown
.../gems/spreadsheet-1.3.0/lib/spreadsheet/excel/writer/worksheet.rb:5: warning: bigdecimal was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec. Also contact author of spreadsheet-1.3.0 to add bigdecimal into its gemspec.
This behaviour is documented with the release of Ruby 3.3.0 https://rubyreferences.github.io/rubychanges/3.3.html#gems-that-are-warned-to-become-bundled-in-the-next-version
=> Fix Ruby 3.3.0 warnings

spreadsheet.gemspec
By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/spreadsheet which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/
=> Provide a 'Changelog' link on rubygems.org/gems/spreadsheet

spreadsheet.gemspec
I noticed that the project already has a FUNDING.yml. This PR adds the `funding_uri` to your gemspec to help increase visibility using the `bundle fund` command in Bundler.
=> Add funding_uri to gemspec

spreadsheet.gemspec
At the moment `changelog_uri` is not displayed, as you can see on [rubygems.org](https://rubygems.org/gems/spreadsheet/versions/1.3.0?locale=en) or on dependabot updates.
I suspect this is because the `changelog_uri` is `https://github.com/zdavatz/spreadsheet//blob/master/History.md` (note the double slash), and it might not pass the regex check.
=> Remove trailing slash from spec.homepage
